// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXxs98denPZ7huq4ywF4lFx_CX8hWRmew',
    appId: '1:211553825024:web:3cdc3e794eed18d30c83e5',
    messagingSenderId: '211553825024',
    projectId: 'sehaty-b82cb',
    authDomain: 'sehaty-b82cb.firebaseapp.com',
    storageBucket: 'sehaty-b82cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvJskoPDR94zUZArKWP-6QRIk-1H8djgI',
    appId: '1:211553825024:android:fa58f43b939025ba0c83e5',
    messagingSenderId: '211553825024',
    projectId: 'sehaty-b82cb',
    storageBucket: 'sehaty-b82cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-bEL-jLOcI3225LTev1XoLZmmJhCnMR8',
    appId: '1:211553825024:ios:8c9890fe9b6459f60c83e5',
    messagingSenderId: '211553825024',
    projectId: 'sehaty-b82cb',
    storageBucket: 'sehaty-b82cb.firebasestorage.app',
    iosClientId: '211553825024-l5d2tol5ha47lgb6p8b5689bfmjsd75d.apps.googleusercontent.com',
    iosBundleId: 'com.example.sehati',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXxs98denPZ7huq4ywF4lFx_CX8hWRmew',
    appId: '1:211553825024:web:1a1c28ba09c048970c83e5',
    messagingSenderId: '211553825024',
    projectId: 'sehaty-b82cb',
    authDomain: 'sehaty-b82cb.firebaseapp.com',
    storageBucket: 'sehaty-b82cb.firebasestorage.app',
  );
}
